#Flexplot: Presented by Sally Larsen, 10/11/2020 slarsen3@une.edu.au
#The preprint explaining the features of the package can be found here:
#Fife, D. (2019, October 16). Flexplot: graphically-based data analysis. 
#https://doi.org/10.31234/osf.io/kh9c3

#Data files are sourced from https://edge.sagepub.com/field5e/student-resources/datasets
#Companion datasets to Field, A. (2018). Discovering Statistics Using IBM SPSS Statistics (5th Ed.).
#Datasets used in this workshop should be in the email where you found this syntax.

#install the stable version of flexplot
#this finally worked (I hope it works for you too)
#A new version of R somehow installed something to make cowplot work too
#you might need to install rtools also
install.packages("rtools")
install.packages)("ggplot2")
install.packages("psych")

devtools::install_github("dustinfife/flexplot")

library(flexplot)
library(ggplot2)
library(psych)
#flexplot plots exist as ggplot2 objects so call ggplot2

setwd ("C:/Users/slarsen3/ownCloud/Documents/Workshops/Flexplot") #add your own directory here

Data1=read.csv("Coldwell et al Data_2006.csv", header=T)
#have a look at the data to see what the variable names are etc.
describe(Data1) #You need the psych package to run this command

#Use flexplot to do some visualizations
#how many girls and boys in this sample?
a = flexplot(child_gender ~ 1, Data1)
plot(a)
#EXACTLY EQUAL NUMBERS!
#Look back at the output from the describe(Data1) command to check if these two pieces of information match
#N.B. 'sdq' variable indicates the 'Strengths and Difficulties Questionnaire'
# 'chaos' variable indicates the 'Confusion, Hubbub and Order Scale'

#Histogram of child age distribution
b = flexplot(child_age ~ 1, Data1)
plot(b)
#SO cool

#Ok, what about histograms of the other variables, in a group of plots
c = flexplot(child_warmth ~ 1, Data1)
d = flexplot(child_anger ~ 1, Data1)
e = flexplot(mum_pos ~ 1, Data1)
f = flexplot(mum_neg ~ 1, Data1)
#This next line places all 4 plots on one image
cowplot::plot_grid(c, d, e, f, nrow=2)

#What about if we have one outcome and one predictor?
#First visualize each variable - this time make the plots APA style
f = flexplot(sdq ~ 1, Data1) +
  labs(x="Strengths & Difficulties", y="count")+
  theme_classic() 
plot(f)
g = flexplot(chaos ~ 1, Data1)+
  labs(x="CHAOS", y="Count")+
  theme_classic()
plot(g)

#Can we make a bivariate scatterplot with a regression line?
h = flexplot(sdq ~ chaos, Data1,
             method = "lm") + #flexplot defaults to a loess line so this bit of code forces a regression line
  labs(x="CHAOS", y="Strengths & Difficulties")+
  theme_classic() 
  plot(h)
#Now try plot h without the method = "lm" command and see what the loess line looks like

#so we have a visual, but what about the parameters?
#Regression equation
model <- lm(chaos ~ sdq, Data1)
summary(model)
#OH.... sad :( 

########################################################################################
#What about visualizing data depending on a category?
#Here we'll use child_gender as the category

i = flexplot(child_anger ~ child_gender, Data1)
plot(i)
#the dot represents the median and the whiskers are the interquartile range
#but these can be changed to spread="stdev" or spread="sterr"
i2 = flexplot(child_anger ~ child_gender, Data1,
             spread = "stdev")+
  labs(x="Gender", y="Anger")
plot(i2)
#You can also alter the jittering of datapoints
#jitter=0.2 is the default
#try jitter=F or jitter=0.1
i3 = flexplot(child_anger ~ child_gender, Data1,
             jitter = 0.1, spread = "stdev")+
            labs(x="Gender", y="Anger")
plot(i3)

#The default is that the labels for gender appear as the codes in the data
#How can we change them to denote M and F?
#in this case we first label the categories like this 
Data1$child_gender = factor(Data1$child_gender, levels = 0:1, 
                            labels = c("M", "F"))
#This command also works if flexplot is reading a categorical variable as continuous

#Then make use of the fact that the flexplot object is a ggplot2 object 
#to change the labels on the x and y axes
i4 = flexplot(child_anger ~ child_gender, Data1,
             jitter = 0.1, spread = "stdev",
             labels = c("M", "F"))+
             labs(x="Gender", y="Anger")+
            theme_classic()  
plot(i4)

#What we're doing here is starting with the basic plot generated by flexplot, then
#building in different features using ggplot2 commands

#here's another example, just for fun.
#the alpha= command changes the colour saturation of the data points
k = flexplot(chaos ~ child_gender, Data1,
             jitter = 0.2, spread = "stdev",
             alpha = 0.6,
             labels = c("M", "F"))+
             labs(x="Gender", y="CHAOS Mean")+
             theme_classic()
plot(k)

###################################################################################
Data2=read.csv("Hill et al Data_2007.csv", header=T)
describe(Data2)

#First make sure flexplot correctly reads the categorical variable for intervention group
Data2$Intervention = factor(Data2$Intervention, ordered=T, #ordered=T makes the groups go in the correct order
                            labels = c("Group 1", "Group 2", "Group 3", "Group 4"))
#Distribution of students within classrooms
a2 = flexplot(Classroom ~ 1, Data2)
plot(a2)
#Distribution of students within intervention groups
b2 = flexplot(Intervention ~ 1, Data2)
plot(b2)
#Distribution of scores on the pre-exercise
c2 = flexplot(Pre_Exercise ~ 1, Data2)
plot(c2)
#Distribution of scores on the post-exercise
d2 = flexplot(Post_Exercise ~ 1, Data2)
plot(d2)

#Of course, you can use the commands in the previous section to change the formating of the figures

#Create a scatterplot with regression line for pre- and post-exercise variables
e2 = flexplot(Pre_Exercise ~ Post_Exercise, Data2,
              method = "lm")
plot(e2)

#Does this regression line look different across the different intervention groups?
f2 = flexplot(Pre_Exercise ~ Post_Exercise | Intervention, Data2,
         method = "lm", 
         ghost.line = "red")
plot(f2)

#Here's another way to look at it:
g2 = flexplot(Pre_Exercise ~ Intervention, Data2,
              spread = "stdev") +
    theme(axis.text.x = element_text(angle=90,size = 12)) #Alter the size of the x-axis text to eliminate overlap
plot(g2)
h2 = flexplot(Post_Exercise ~ Intervention, Data2,
              spread = "stdev")+
  theme(axis.text.x = element_text(angle=90, size = 12))
plot(h2)
cowplot::plot_grid(g2, h2)


###########################################################################
#PLOTTING REPEATED MEASURES DATA

#Here let's imagine that the 'Intervention' variable is a repeated measures identifier
#In this case 1 = time 1; 2 = time 2 etc. 
#We'll use the 'Post_Exercise' variable as the outcome (ostensibly measured repeatedly)
#First take the labels off the data for the intervention groups
Data2=read.csv("Hill et al Data_2007.csv", header=T)
describe(Data2)
#Now we'll re-label them as time intervals (remember, we're just pretending with this example)
Data2$Intervention = factor(Data2$Intervention, ordered=T, #ordered=T makes the times go in the correct order
                            labels = c("Time 1", "Time 2", "Time 3", "Time 4"))

#Now we're going to plot the data at the 4 'times' and put a line linking the means to 
#see if there's a trend

I2 = flexplot(Post_Exercise~Intervention, data=Data2, jitter =.2, spread = "stdev",
                alpha = .06) #this alpha command alters the colour saturation of the data points
plot (I2)
#You don't have to re-run the whole section to create plot I2 again
#You can simply add new ggplot2 funtions like this:
I2 + stat_summary(fun.y=mean, colour="blue", geom="line", linetype="dotted", size=1,
                    aes(group=1)) +
  labs(x="", y="Score") +
  theme_classic()+
  theme(axis.text.x = element_text(angle=90, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12))

#the stat_summary parentheses is where you alter the line properties 
#try omitting linetype to see what the default is 
#try changing the size and colour of the line
#just omit stat_summary if you don't want a line connecting means
#labs is where you alter axis labels
#theme_classic makes it APA style - there's other themes
#theme(axis.text.x = ) - this is where you change the font size of axis labels
#Please remind me to show you another example of a repeated measures plot
###################################################################################
Data3=read.csv("Ong et al Data_2011.csv", header=T)
describe(Data3)
#Variables: NEO_FFI is 'extroversion' and 
# NPQC_R is 'narcissism'
Data3$Gender = factor(Data3$Gender, levels = 0:1, 
                      labels = c("M", "F"))

#Now visualize the continuous variables
a3 = flexplot(NEO_FFI ~ 1, Data3)
plot(a3)
b3 = flexplot(NPQC_R ~ 1, Data3)
plot(b3)
c3 = flexplot(FB_Status ~ 1, Data3)
plot(c3)
d3 = flexplot(FB_Profile_TOT ~ 1, Data3)
plot(d3)
cowplot::plot_grid(a3, b3, c3, d3, nrow=2)
#alter each of the plots as in previous sections to change the formatting


#Added variable plot - where you have more than 1 predictor - 1 categorical predictor
#if the research question is: do both extraversion and gender predict the 
#total number of facebook profile updates

e3 = flexplot(FB_Profile_TOT ~ NEO_FFI + Gender, Data3,
              method="lm")+
  labs(x="Extroversion", y="Facebook Updates")+
  theme(axis.text.x = element_text(size = 12),
        axis.text.y.left = element_text(size = 12))
plot(e3)

#Alternatively you can make one plot for each category (i.e. gender)
#and include a 'ghost line' to compare the regression lines across categories
f3 = flexplot(FB_Profile_TOT ~ NEO_FFI | Gender, Data3,
              method = "lm", ghost.line = "red")+
            labs(x="Extroversion", y="Facebook Updates")
plot(f3)

#In this case, I kind of prefer plot e3, partly because there are only 2 categories.
#Also this is how you would plot an interaction or a moderation.

#Added variable plot - two continuous predictors
g3 = flexplot(FB_Profile_TOT ~ NEO_FFI + NPQC_R, Data3,
              method="lm")+
  labs(x="Extroversion", y="Facebook Updates")+
  theme_classic()+
  theme(axis.text.x = element_text(size = 12),
        axis.text.y.left = element_text(size = 12))
plot(g3)

#Does anyone know how to change the text on the right hand label indicating the 'bins'?

#here is another possibility for plotting the same data
h3 = flexplot(FB_Profile_TOT ~ NEO_FFI | NPQC_R, Data3,
              method="lm", ghost.line = "red",
              labels=list(NPQC_R=c("low", "medium", "high")))+
  labs(x="Extroversion", y="Facebook Updates")
plot(h3)

#There are a lot more examples in the paper cited at the start of this syntax!